# Generated by Django 5.1.3 on 2024-12-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="date",
        ),
    ]
